name: Build & Test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      fhenix:
        # Docker image
        image: ghcr.io/fhenixprotocol/fhenix-node-dev:v0.0.7-standalone
        ports:
          # Opens tcp port
          - 3000:3000
          - 8548:8548
          - 8547:8547
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: "Install Pnpm"
        uses: "pnpm/action-setup@v2"
        with:
          version: "8"
      - name: Build go-tfhe
        run: |
          cd go-tfhe && make build-rust
      - name: Install Dependencies
        run: |
          make install
      - name: Make gen
        run: |
          make gen
      - name: Compile
        run: |
          cp solidity/.env.example solidity/.env
          make compile
      - name: Run tests
        run: |
          make test
      
      - name: Package Contracts
        run: |
          tar -cvf contracts.tar solidity/tests/contracts/ solidity/FHE.sol solidity/FheOS.sol
      - uses: actions/upload-artifact@v3
        name: Store contracts
        with:
          name: contracts.tar
          path: contracts.tar

  push-to-contracts-repo:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/Cashmaney-test-ci-1' }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout Fhenix-Contracts
        with:
          repository: FhenixProtocol/fhenix-contracts
          ref: 'main'
          token:  ${{ secrets.GH_PAT }}
      - name: Parse GH Commit Hash
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - uses: actions/download-artifact@v3
        with:
          name: contracts.tar
          path: .
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "noreply@github.com"
      - name: Copy test contracts & Generated libs
        run: |
          ls -l
          mkdir -p test/automated/contracts
          mkdir temp_extraction
          tar -xvf contracts.tar -C temp_extraction
          mv temp_extraction/solidity/FHE.sol temp_extraction/solidity/FheOS.sol contracts/
      - name: Commit Changes
        run: |
          git add contracts/FHE.sol
          git add contracts/FheOS.sol
          git commit -m "FheOS updated - pushing new contracts and scripts"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: Updated Contracts from FheOS
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: fheos-${{ env.sha_short }}
          delete-branch: true
          title: 'Update Contracts from FheOS'
          body: |
            Updated contracts from FheOS push to [master](https://github.com/fhenixprotocol/fheos/commit/"$GITHUB_SHA")
          labels: |
            report
            automated pr
          draft: false
