name: Push to Other Repo

on:
  push:
    branches: "*"
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      fhenix:
        # Docker image
        image: ghcr.io/fhenixprotocol/fhenix-node-dev:v0.0.6-standalone
        ports:
          # Opens tcp port
          - 3000:3000
          - 8548:8548
          - 8547:8547
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: fheos
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: "Install Pnpm"
        uses: "pnpm/action-setup@v2"
        with:
          version: "8"
      - name: Build go-tfhe
        run: |
          cd fheos/go-tfhe && make build-rust
      # todo: replace this with the command from the makefile after lior makes it not depend on nitro repo
      - run: |
          cd fheos
          FHE_OPS_DEST=${1:-"../precompiles"}
          OUTPUT=${2:-"chains/arbitrum"}
          
          go run gen.go 1
          if [ ! -e precompiles/contracts ]; then
              mkdir precompiles/contracts
          fi
          cp FheOs_gen.sol precompiles/contracts/FheOs.sol
          mv FheOs_gen.sol solidity/FheOS.sol
          cd precompiles
          rm -rf artifacts
          yarn
          yarn build
          rm -r ./contracts/
          cd ../
          go run gen.go 2 $OUTPUT
          rm *_gen*
      - name: Run tests
        run: |
          cd fheos && make test
      - uses: actions/checkout@v4
        name: Checkout Fhenix-Contracts
        with:
          repository: FhenixProtocol/fhenix-contracts
          path: fhenix-contracts
          ref: 'main'
          token:  ${{ secrets.GH_PAT }}
      - name: setup git config
        run: |
          cd fhenix-contracts
          git config user.name "GitHub Actions Bot"
          git config user.email "noreply@github.com"
      - name: Copy test contracts & Generated libs
        run: |
          ls -l
          mkdir -p fhenix-contracts/test/automated/contracts
          cp -r fheos/solidity/tests/contracts/* fhenix-contracts/test/automated/contracts/*
          cp fheos/solidity/FHE.sol fhenix-contracts/contracts/
          cp fheos/solidity/FheOS.sol fhenix-contracts/contracts/
      - name: Commit Changes
        run: |
          cd fhenix-contracts
          git checkout -b automated
          git add test/contracts/*
          git add contracts/FHE.sol
          git add contracts/FheOS.sol
          git commit -m "FheOS updated - pushing new contracts and scripts"
      - name: create pull request
        #if: blah blah
        run: cd fhenix-contracts && gh pr create -B automated -H main --title 'Merge automated into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
